version: "3.9"

services:
  postgres:
    image: postgres
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    volumes:
      - ./data-postgres:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 2s
      timeout: 20s
      retries: 120

networks:
  default:
    external: true
    name: "ecommerce-local"
